# program:
#   log_file_path: ./output.log

rabbitmq:
  user: $RABBITMQ_USER
  pass: $RABBITMQ_PASS
  host: $RABBITMQ_HOST
  port: ${RABBITMQ_PORT}


resources:
  exchanges:
    - name: sphinx_indexer_exchange
      type: direct
      durable: true
      auto_deleted: false
      internal: false
      no_wait: true


commands:
  product_variant_main:
    resource: sphinx_indexer_exchange
    routing_key: product_variant_main
    command_pre: echo "product_variant_main pre"
    command: |
      /opt/sphinx/sphinx-3.1.1/bin/indexer --config $SPHINX_CONFIG_PATH --rotate product_variant_main
    command_post: echo "product_variant_main post"


  product_admin:
    resource: sphinx_indexer_exchange
    routing_key: product_admin
    command_pre: echo "product_admin pre"
    command: |
      /opt/sphinx/sphinx-3.1.1/bin/indexer --config $SPHINX_CONFIG_PATH --rotate product_admin
    command_post: echo "product_admin post"


  product_variant_admin_inch:
    resource: sphinx_indexer_exchange
    routing_key: product_variant_admin_inch
    command_pre: echo "product_variant_admin_inch pre"
    command: |
      /opt/sphinx/sphinx-3.1.1/bin/indexer --config $SPHINX_CONFIG_PATH --rotate product_variant_admin_inch
    command_post: echo "product_variant_admin_inch post"