# program:
  # log_file_path: ./output.log


resources:
  exchanges:
    - name: sphinx_indexer_exchange
      type: direct
      durable: true
      auto_deleted: false
      internal: false
      no_wait: false


commands:
  product_variant_main:
    resource: sphinx_indexer_exchange
    routing_key: product_variant_main
    command_pre: echo "product_variant_main pre"
    command: echo "product_variant_main command"
    command_post: echo "product_variant_main post"


  product_admin:
    resource: sphinx_indexer_exchange
    routing_key: product_admin
    command_pre: echo "product_admin pre"
    command: echo "product_admin command"
    command_post: echo "product_admin post"


  product_variant_admin_inch:
    resource: sphinx_indexer_exchange
    routing_key: product_variant_admin_inch
    command_pre: echo "product_variant_admin_inch pre"
    command: echo "product_variant_admin_inch command"
    command_post: echo "product_variant_admin_inch post"